const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content");
const OUT_FILE = path.join(ROOT, "assets", "generated-content.js");

const COLLECTIONS = ["posts", "projects", "retrospectives", "features", "thoughts", "work"];

function readJson(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  return JSON.parse(raw);
}

function normalizeItem(item, collection, fileName) {
  const slugFromFile = fileName.replace(/\.json$/i, "");
  return {
    title: item.title || slugFromFile,
    slug: item.slug || slugFromFile,
    collection,
    type: item.type || collection.slice(0, -1),
    date: item.date || "",
    status: item.status || "",
    summary: item.summary || "",
    tags: Array.isArray(item.tags) ? item.tags : [],
    icon: item.icon || "/images/post-icons/default.svg",
    heroImage: item.heroImage || "",
    featured: Boolean(item.featured),
    sections: Array.isArray(item.sections) ? item.sections : []
  };
}

function buildContent() {
  const collections = {};
  const all = [];

  for (const collection of COLLECTIONS) {
    const dir = path.join(CONTENT_DIR, collection);
    fs.mkdirSync(dir, { recursive: true });
    const files = fs.readdirSync(dir).filter((file) => file.endsWith(".json"));

    collections[collection] = files.map((file) => {
      const filePath = path.join(dir, file);
      const item = normalizeItem(readJson(filePath), collection, file);
      all.push(item);
      return item;
    }).sort(sortByDateDesc);
  }

  all.sort(sortByDateDesc);

  const payload = {
    generatedAt: new Date().toISOString(),
    collections,
    all
  };

  const js = `// This file is generated by scripts/build-content.js. Do not edit by hand.\nwindow.SITE_CONTENT = ${JSON.stringify(payload, null, 2)};\n`;
  fs.writeFileSync(OUT_FILE, js, "utf8");
  return payload;
}

function sortByDateDesc(a, b) {
  return String(b.date || "").localeCompare(String(a.date || ""));
}

if (require.main === module) {
  try {
    const payload = buildContent();
    console.log(`generated assets/generated-content.js with ${payload.all.length} items`);
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

module.exports = { buildContent, COLLECTIONS };
