const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content");
const OUT_FILE = path.join(ROOT, "assets", "generated-content.js");
const INDEX_FILE = path.join(ROOT, "index.template.html");

const COLLECTIONS = ["posts", "projects", "retrospectives", "features", "thoughts", "work"];

const SITE_URL = "https://www.blaylock.io";

const DEFAULT_OG = {
  title: "Darren Blaylock",
  description: "Projects, thoughts, notes, retrospectives, and work.",
  image: "/images/site-preview.png",
  url: SITE_URL
};

function cleanPlacements(value) {
  if (!Array.isArray(value)) return [];

  return [...new Set(value)]
    .filter(collection => COLLECTIONS.includes(collection));
}

function escapeHtmlAttr(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}



function absoluteUrl(value = "") {
  if (!value) return SITE_URL;
  if (/^https?:\/\//.test(value)) return value;
  return `${SITE_URL}${value.startsWith("/") ? value : `/${value}`}`;
}

function applyOgTags(html, og) {
  return html
    .replaceAll("{{OG_TITLE}}", escapeHtmlAttr(og.title || DEFAULT_OG.title))
    .replaceAll("{{OG_DESCRIPTION}}", escapeHtmlAttr(og.description || DEFAULT_OG.description))
    .replaceAll("{{OG_IMAGE}}", escapeHtmlAttr(absoluteUrl(og.image || DEFAULT_OG.image)))
    .replaceAll("{{OG_URL}}", escapeHtmlAttr(absoluteUrl(og.url || DEFAULT_OG.url)));
}

function postUrl(item) {
  return `/${item.collection}/${item.slug}`;
}


function findFirstImage(item) {
  const imageSection = (item.sections || []).find(section => {
    return section.type === "image" && section.src;
  });

  return imageSection?.src || "";
}

function readJson(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  return JSON.parse(raw);
}

function normalizeItem(item, collection, fileName) {
  const slugFromFile = fileName.replace(/\.json$/i, "");
  const placements = cleanPlacements(
    Array.isArray(item.placements)
      ? item.placements
      : item.featured
        ? ["features"]
        : []
  );

  const normalized = {
    title: item.title || slugFromFile,
    slug: item.slug || slugFromFile,
    collection,
    type: item.type || collection.slice(0, -1),
    date: item.date || "",
    status: item.status || "",
    summary: item.summary || "",
    tags: Array.isArray(item.tags) ? item.tags : [],
    icon: item.icon || "/images/post-icons/default.svg",
    heroImage: item.heroImage || "",
    placements,
    featured: placements.includes("features"),
    badge: item.badge || "",
    sections: Array.isArray(item.sections) ? item.sections : []
  };

  normalized.thumbnail =
    item.thumbnail ||
    findFirstImage(normalized) ||
    "/images/site-preview.png";

  return normalized;
}
function sortByDateDesc(a, b) {
  return String(b.date || "").localeCompare(String(a.date || ""));
}

function writeRouteIndex(routePath, og = DEFAULT_OG) {
  const baseHtml = fs.readFileSync(INDEX_FILE, "utf8");
  const html = applyOgTags(baseHtml, og);

  const outDir = path.join(ROOT, routePath);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "index.html"), html, "utf8");
}

function cleanGeneratedRoutes() {
  for (const collection of COLLECTIONS) {
    const routeDir = path.join(ROOT, collection);

    if (fs.existsSync(routeDir)) {
      fs.rmSync(routeDir, { recursive: true, force: true });
    }
  }
}

function buildContent() {
  const collections = {};
  const all = [];

  for (const collection of COLLECTIONS) {
    const dir = path.join(CONTENT_DIR, collection);
    fs.mkdirSync(dir, { recursive: true });

    const files = fs.readdirSync(dir).filter((file) => file.endsWith(".json"));

    collections[collection] = files
      .map((file) => {
        const filePath = path.join(dir, file);
        const item = normalizeItem(readJson(filePath), collection, file);
        all.push(item);
        return item;
      })
      .sort(sortByDateDesc);
  }

  all.sort(sortByDateDesc);

  const payload = {
    generatedAt: new Date().toISOString(),
    collections,
    all
  };

  const js = `// This file is generated by scripts/build-content.js. Do not edit by hand.\nwindow.SITE_CONTENT = ${JSON.stringify(payload, null, 2)};\n`;

  fs.writeFileSync(OUT_FILE, js, "utf8");

  cleanGeneratedRoutes();

  for (const collection of COLLECTIONS) {
    writeRouteIndex(collection, {
      title: `${collection} — Darren Blaylock`,
      description: `Browse ${collection} on blaylock.io.`,
      image: DEFAULT_OG.image,
      url: `/${collection}`
    });

    for (const item of collections[collection] || []) {
      writeRouteIndex(path.join(collection, item.slug), {
        title: item.title || DEFAULT_OG.title,
        description: item.summary || DEFAULT_OG.description,
        image: item.thumbnail || DEFAULT_OG.image,
        url: postUrl(item)
      });
    }
  }

  return payload;
}

if (require.main === module) {
  try {
    const payload = buildContent();
    console.log(`generated assets/generated-content.js with ${payload.all.length} items`);
    console.log("generated static route folders for collections and posts");
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

module.exports = { buildContent, COLLECTIONS };